

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fa' | 'en';
type Direction = 'rtl' | 'ltr';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fa: {
    app_title: 'آب‌بان',
    app_subtitle: 'سامانه هوشمند پایش و مدیریت ورشکستگی آبی',
    nav_home: 'صفحه اصلی',
    nav_dashboard: 'داشبورد منابع آب',
    nav_chat: 'مشاور هیدرولوژی (AI)',
    nav_finetuning: 'مدل‌سازی آبخوان',
    nav_resources: 'قوانین و استانداردها',
    nav_wp: 'پنل گزارشات مردمی',
    nav_erp: 'تله‌متری و اسکادا',
    nav_checklists: 'بازرسی چاه و تأسیسات',
    nav_vegetation: 'مدیریت پوشش گیاهی',
    nav_hydromap: 'تحلیل علمی (HydroMap)',
    stats_today: 'وضعیت آبی کشور',
    role_manager: 'مدیر حفاظت و بهره‌برداری',
    stat_docs: 'ذخیره سدها (MCM)',
    stat_discrepancies: 'دشت‌های بحرانی',
    stat_fraud: 'چاه‌های غیرمجاز',
    stat_score: 'بارندگی (mm)',
    
    // Landing Page
    landing_hero_title: 'مدیریت هوشمند بحران آب',
    landing_hero_desc: 'آب‌بان، پلتفرم جامع پایش آبخوان‌ها، کنترل مصرف کشاورزی و پیشگیری از فرونشست زمین با استفاده از هوش مصنوعی.',
    landing_cta_start: 'ورود به پنل پایش',
    landing_cta_demo: 'مشاهده وضعیت دشت‌ها',
    landing_code_title: 'تحلیل سطح پیزومترها',
    landing_feat_1_title: 'تعادل‌بخشی آبخوان',
    landing_feat_1_desc: 'محاسبه بیلان آب و حجم مجاز برداشت برای هر دشت',
    landing_feat_2_title: 'پایش کنتورهای هوشمند',
    landing_feat_2_desc: 'قرائت لحظه‌ای چاه‌های کشاورزی و قطع برق در صورت تخلف',
    landing_feat_3_title: 'پایش فرونشست',
    landing_feat_3_desc: 'تحلیل داده‌های راداری (InSAR) برای شناسایی مناطق خطر',
    
    // Company Info
    company_info_title: 'درباره آب‌بان',
    company_desc: 'توسعه‌دهنده راهکارهای فناورانه برای نجات منابع آب زیرزمینی و مدیریت حوضه آبریز.',
    contact_address_label: 'آدرس',
    contact_address: 'تهران، وزارت نیرو، شرکت مدیریت منابع آب',
    contact_email_label: 'ایمیل',
    contact_phone_label: 'تلفن',

    // Fine Tuning (Aquifer Modeling)
    ft_tab_studio: 'استودیو مدل‌سازی',
    ft_tab_dashboard: 'نتایج پیش‌بینی',
    ft_studio_title: 'شبیه‌سازی هیدروژئولوژیکی',
    ft_studio_desc: 'آموزش مدل‌های هوش مصنوعی برای پیش‌بینی رفتار آبخوان در خشکسالی',
    ft_dash_title: 'پیش‌بینی سطح آب',
    ft_dash_desc: 'مقایسه سناریوهای تغذیه مصنوعی و کاهش برداشت',
    ft_connect_wb: 'اتصال به شبکه پایش',
    ft_connect_desc: 'داده‌های پیزومترها و باران‌سنج‌ها در حال پردازش است.',
    ft_view_dash: 'نقشه ایزوپیز',
    ft_step_1: 'داده‌های ورودی',
    ft_drop_file: 'فایل اکسل پیزومترها (Piezometer Data) را آپلود کنید',
    ft_test_data: 'داده‌های نمونه (دشت قزوین)',
    ft_step_2: 'پارامترهای مدل',
    ft_model_name: 'نام سناریو',
    ft_epochs: 'دوره‌های شبیه‌سازی',
    ft_batch_size: 'تفکیک هیدرولوژیک',
    ft_start_btn: 'شروع شبیه‌سازی',
    ft_training: 'در حال حل معادلات جریان...',
    ft_progress: 'پیشرفت مدل MODFLOW',
    ft_logs: 'لاگ‌های سرور محاسباتی',
    ft_convergence: 'نمودار واسنجی (Calibration)',
    
    ft_kpi_runs: 'سناریوهای اجرا شده',
    ft_kpi_acc: 'دقت مدل (RMSE)',
    ft_kpi_time: 'زمان پردازش',
    ft_kpi_res: 'حجم صرفه‌جویی',
    ft_list_title: 'تاریخچه مدل‌سازی‌ها',
    ft_search: 'جستجوی آبخوان...',
    ft_col_name: 'سناریو',
    ft_col_acc: 'ضریب همبستگی',
    ft_chart_metrics: 'تحلیل حساسیت',
    ft_chart_pred: 'سطح ایستابی: مشاهده vs مدل',
    ft_col_input: 'محدوده مطالعاتی',
    ft_col_label: 'کسری مخزن',
    ft_sys_metrics: 'وضعیت لاگرها',

    // Resources
    res_title: 'قوانین و دستورالعمل‌های بخش آب',
    res_subtitle: 'قانون توزیع عادلانه آب و استانداردهای وزارت نیرو',
    res_sec_templates: 'فرم‌های بازرسی',
    res_sec_definitions: 'تعاریف پایه',
    res_dl_excel: 'دانلود لیست چاه‌ها (Excel)',
    res_dl_pdf: 'دستورالعمل تعیین حریم (PDF)',
    res_def_balance: 'آبخوان (Aquifer)',
    res_desc_balance: 'لایه آب‌دار زیرزمینی که قابلیت انتقال آب دارد.',
    res_def_pl: 'آب تجدیدپذیر',
    res_desc_pl: 'مجموع بارش منهای تبخیر که وارد منابع آب می‌شود.',
    res_def_cash: 'فرونشست (Subsidence)',
    res_desc_cash: 'فرو ریختن سطح زمین به دلیل خالی شدن آبخوان‌ها.',
    res_erp_title: 'سامانه حفاظت',
    res_erp_desc: 'دسترسی به سامانه ساماب و بانک اطلاعاتی چاه‌ها.',
    
    // Municipality Connect -> SCADA Connect
    erp_title: 'اتصال به سامانه تله‌متری',
    erp_subtitle: 'دریافت مستقیم اطلاعات کنتورهای هوشمند فهام و دیتالاگرها',
    erp_login_server: 'آدرس سرور SCADA',
    erp_login_user: 'کد اپراتور',
    erp_login_pass: 'رمز عبور',
    erp_btn_connect: 'اتصال به شبکه',
    erp_status_connected: 'ارتباط برقرار است',
    erp_status_sync: 'آخرین پکت: ۱۰ ثانیه پیش',
    erp_dash_revenue: 'حجم برداشت امروز',
    erp_dash_expense: 'تعداد چاه فعال',
    erp_dash_net: 'میانگین دبی لحظه‌ای',
    erp_vouchers_title: 'آخرین لاگ‌های تله‌متری',
    erp_col_id: 'شماره پرونده',
    erp_col_desc: 'نام دشت',
    erp_col_date: 'زمان قرائت',
    erp_col_amount: 'کارکرد (مترمکعب)',
    erp_col_status: 'وضعیت کنتور',
    erp_btn_fetch: 'بروزرسانی داده‌ها',
    erp_loading: 'دریافت داده از مودم‌ها...',

    // Checklist Manager
    chk_title: 'بازرسی و گشت‌زنی',
    chk_subtitle: 'چک‌لیست‌های گروه‌های گشت و بازرسی منابع آب',
    chk_btn_create: 'برگ ماموریت جدید',
    chk_list_empty: 'لیستی موجود نیست.',
    chk_card_items: 'آیتم کنترلی',
    chk_btn_assign: 'تخصیص به گروه گشت',
    chk_btn_edit: 'ویرایش',
    chk_btn_delete: 'حذف',
    chk_modal_title: 'ویرایش چک‌لیست بازرسی',
    chk_label_title: 'منطقه',
    chk_label_desc: 'شرح ماموریت',
    chk_sec_items: 'موارد بازرسی',
    chk_ph_item: 'مورد جدید (مثلا: کنترل پروانه)...',
    chk_btn_add_item: 'افزودن',
    chk_col_mandatory: 'توقیف دستگاه',
    chk_btn_save: 'ذخیره',
    chk_btn_cancel: 'انصراف',

    // Vegetation Manager
    veg_title: 'مدیریت پوشش گیاهی و آبخیزداری',
    veg_subtitle: 'تحلیل هوشمند اراضی برای کاشت درخت و تغذیه آبخوان',
    veg_intro_title: 'احیای دشت‌ها با پوشش گیاهی',
    veg_intro_desc: 'استفاده از هوش مصنوعی برای انتخاب بهترین گونه‌های گیاهی سازگار با اقلیم خشک، جهت کاهش فرسایش خاک، افزایش نفوذپذیری آب باران و جلوگیری از ریزگردها.',
    veg_tab_region: 'تحلیل منطقه‌ای',
    veg_tab_vision: 'تحلیل تصویری (ماهواره/پهپاد)',
    veg_tab_map: 'نقشه جغرافیایی',
    veg_input_placeholder: 'نام منطقه یا دشت (مثال: دشت قزوین)...',
    veg_btn_analyze: 'دریافت طرح کاشت',
    veg_upload_label: 'تصویر زمین یا نقشه ماهواره‌ای را بارگذاری کنید',
    veg_prompt_label: 'سوال شما از هوش مصنوعی (اختیاری)',
    veg_prompt_placeholder: 'چه نوع درختانی برای تثبیت خاک این شیب مناسب است؟',
    veg_btn_vision: 'تحلیل تصویر',
    veg_result_title: 'پیشنهاد هوش مصنوعی',
    veg_region_empty: 'برای دریافت برنامه کاشت، نام منطقه را وارد کنید.',
    veg_map_instr: 'برای دریافت پیش‌بینی آب‌وهوا و وضعیت آب زیرزمینی، روی نقشه کلیک کنید.',
    veg_btn_map_analyze: 'تحلیل اقلیمی و آبی این نقطه',
    veg_btn_history: 'تحلیل روند ۵ ساله (NDVI)',
    veg_lat: 'عرض جغرافیایی',
    veg_lng: 'طول جغرافیایی',

    // HydroMap Manager
    hydro_title: 'HydroMap AI',
    hydro_subtitle: 'پلتفرم پیشرفته تحلیل‌های هیدرو-اقلیمی',
    hydro_mode_point: 'تحلیل نقطه‌ای',
    hydro_mode_basin: 'تحلیل حوضه آبریز',
    hydro_loading_analysis: 'در حال اجرای مدل‌های هیدرولوژی...',
    hydro_chart_title: 'روند تاریخی سطح آب (شبیه‌سازی NDWI)',
    hydro_basin_area: 'مساحت حوضه',
    hydro_basin_perim: 'محیط حوضه',
    hydro_tab_climate: 'پیش‌بینی اقلیمی (Open-Meteo)',
    hydro_tab_hydro: 'وضعیت هیدرولوژی',
    hydro_tab_recs: 'پیشنهادات هوش مصنوعی',


    // Dashboard
    dash_live: 'پایش زنده آبخوان',
    dash_static: 'بیلان منابع آب',
    dash_planning: 'تخصیص و برنامه‌ریزی',
    dash_executive: 'مدیریت بحران',
    chat_placeholder: 'سوال درباره وضعیت دشت‌ها یا قوانین آبی...',
    chat_send: 'ارسال',
    chat_clear: 'پاکسازی',
    chat_processing: 'تحلیل هیدرولوژیکی...',
    chat_welcome: 'من آب‌بان هستم. وضعیت کدام دشت را بررسی کنم؟',
    chat_response: 'پاسخ کارشناس هوشمند',

    // CMS (People Reports)
    wp_dashboard: 'گزارشات تخلفات',
    wp_home: 'پورتال حفاظت',
    wp_updates: 'پیام‌های مردمی',
    wp_posts: 'اخبار خشکسالی',
    wp_media: 'گالری تصاویر',
    wp_pages: 'اطلاعیه‌های قطع آب',
    wp_comments: 'نظرات کشاورزان',
    wp_appearance: 'پوسته',
    wp_plugins: 'ماژول‌ها',
    wp_users: 'کاربران',
    wp_tools: 'ابزارها',
    wp_settings: 'تنظیمات',
    wp_welcome_title: 'سامانه سوت‌زنی تخلفات آبی',
    wp_welcome_subtitle: 'رسیدگی به گزارشات چاه‌های غیرمجاز و برداشت‌های بی‌رویه.',
    wp_at_a_glance: 'خلاصه گزارشات',
    wp_activity: 'آخرین تخلفات ثبت شده',
    wp_quick_draft: 'ثبت صورتجلسه',
    wp_news: 'اخبار وزارت نیرو',
    wp_title_placeholder: 'موضوع تخلف',
    wp_content_placeholder: 'شرح واقعه...',
    wp_save_draft: 'ذخیره موقت',
  },
  en: {
    app_title: 'AbBaan',
    app_subtitle: 'Water Bankruptcy Management AI',
    nav_home: 'Home',
    nav_dashboard: 'Water Resources Dash',
    nav_chat: 'Hydro AI Consultant',
    nav_finetuning: 'Aquifer Modeling',
    nav_resources: 'Laws & Standards',
    nav_wp: 'Public Reports (CMS)',
    nav_erp: 'Telemetry & SCADA',
    nav_checklists: 'Inspection Checklists',
    nav_vegetation: 'Vegetation & Catchment',
    nav_hydromap: 'Scientific Analysis (HydroMap)',
    stats_today: 'National Water Status',
    role_manager: 'Water Resource Manager',
    stat_docs: 'Dam Reserves (MCM)',
    stat_discrepancies: 'Critical Plains',
    stat_fraud: 'Illegal Wells',
    stat_score: 'Rainfall (mm)',
    
    landing_hero_title: 'Smart Water Crisis Management',
    landing_hero_desc: 'AbBaan is a comprehensive platform for monitoring aquifers, controlling agricultural consumption, and preventing land subsidence using AI.',
    landing_cta_start: 'Enter Monitoring Panel',
    landing_cta_demo: 'View Plains Status',
    landing_code_title: 'Piezometer Level Analysis',
    landing_feat_1_title: 'Aquifer Balancing',
    landing_feat_1_desc: 'Calculate water balance and allowable withdrawal for each plain',
    landing_feat_2_title: 'Smart Meter Monitoring',
    landing_feat_2_desc: 'Real-time reading of agricultural wells and remote cut-off',
    landing_feat_3_title: 'Subsidence Monitoring',
    landing_feat_3_desc: 'InSAR radar data analysis to identify risk zones',

    company_info_title: 'About AbBaan',
    company_desc: 'Developing technological solutions for saving groundwater resources and watershed management.',
    contact_address_label: 'Address',
    contact_address: 'Tehran, Ministry of Energy, Water Resources Management Co.',
    contact_email_label: 'Email',
    contact_phone_label: 'Phone',

    ft_tab_studio: 'Modeling Studio',
    ft_tab_dashboard: 'Prediction Dashboard',
    ft_studio_title: 'Hydrogeological Simulation',
    ft_studio_desc: 'Train AI models to predict aquifer behavior under drought',
    ft_dash_title: 'Water Level Prediction',
    ft_dash_desc: 'Compare artificial recharge and withdrawal reduction scenarios',
    ft_connect_wb: 'Connect to Monitoring Network',
    ft_connect_desc: 'Processing piezometer and rain gauge data.',
    ft_view_dash: 'Iso-Piezometric Map',
    ft_step_1: 'Input Data',
    ft_drop_file: 'Upload Piezometer Excel File',
    ft_test_data: 'Sample Data (Qazvin Plain)',
    ft_step_2: 'Model Parameters',
    ft_model_name: 'Scenario Name',
    ft_epochs: 'Simulation Epochs',
    ft_batch_size: 'Hydrologic Batching',
    ft_start_btn: 'Start Simulation',
    ft_training: 'Solving flow equations...',
    ft_progress: 'MODFLOW Progress',
    ft_logs: 'Compute Server Logs',
    ft_convergence: 'Calibration Chart',
    
    ft_kpi_runs: 'Scenarios Run',
    ft_kpi_acc: 'Model Accuracy (RMSE)',
    ft_kpi_time: 'Processing Time',
    ft_kpi_res: 'Volume Saved',
    ft_list_title: 'Modeling History',
    ft_search: 'Search Aquifer...',
    ft_col_name: 'Scenario',
    ft_col_acc: 'Correlation',
    ft_chart_metrics: 'Sensitivity Analysis',
    ft_chart_pred: 'Water Table: Obs vs Model',
    ft_col_input: 'Study Area',
    ft_col_label: 'Reservoir Deficit',
    ft_sys_metrics: 'Logger Status',

    res_title: 'Water Laws & Directives',
    res_subtitle: 'Fair Water Distribution Law and Ministry Standards',
    res_sec_templates: 'Inspection Forms',
    res_sec_definitions: 'Basic Definitions',
    res_dl_excel: 'Download Wells List (Excel)',
    res_dl_pdf: 'Buffer Zone Guidelines (PDF)',
    res_def_balance: 'Aquifer',
    res_desc_balance: 'Underground layer capable of yielding water.',
    res_def_pl: 'Renewable Water',
    res_desc_pl: 'Total precipitation minus evaporation entering water sources.',
    res_def_cash: 'Subsidence',
    res_desc_cash: 'Sinking of land surface due to aquifer depletion.',
    res_erp_title: 'Protection System',
    res_erp_desc: 'Access to SAMAB system and wells database.',

    erp_title: 'Telemetry Connection',
    erp_subtitle: 'Direct fetch from FAHAM smart meters and data loggers',
    erp_login_server: 'SCADA Server',
    erp_login_user: 'Operator ID',
    erp_login_pass: 'Password',
    erp_btn_connect: 'Connect',
    erp_status_connected: 'Connected',
    erp_status_sync: 'Last Packet: 10s ago',
    erp_dash_revenue: 'Withdrawal Today',
    erp_dash_expense: 'Active Wells',
    erp_dash_net: 'Avg Flow Rate',
    erp_vouchers_title: 'Recent Telemetry Logs',
    erp_col_id: 'File Number',
    erp_col_desc: 'Plain Name',
    erp_col_date: 'Reading Time',
    erp_col_amount: 'Usage (m3)',
    erp_col_status: 'Meter Status',
    erp_btn_fetch: 'Refresh Data',
    erp_loading: 'Fetching from modems...',

    chk_title: 'Patrol & Inspection',
    chk_subtitle: 'Checklists for Water Patrol Teams',
    chk_btn_create: 'New Mission Sheet',
    chk_list_empty: 'No checklists.',
    chk_card_items: 'Control Item',
    chk_btn_assign: 'Assign to Patrol',
    chk_btn_edit: 'Edit',
    chk_btn_delete: 'Delete',
    chk_modal_title: 'Edit Inspection Checklist',
    chk_label_title: 'Region',
    chk_label_desc: 'Mission Description',
    chk_sec_items: 'Inspection Items',
    chk_ph_item: 'New item (e.g. Check Permit)...',
    chk_btn_add_item: 'Add',
    chk_col_mandatory: 'Seize Equipment',
    chk_btn_save: 'Save',
    chk_btn_cancel: 'Cancel',

    veg_title: 'Vegetation & Watershed Mgmt',
    veg_subtitle: 'AI Analysis for Afforestation and Aquifer Recharge',
    veg_intro_title: 'Reviving Plains with Vegetation',
    veg_intro_desc: 'Using AI to select drought-resistant plant species to reduce soil erosion, increase rainwater infiltration, and prevent dust storms.',
    veg_tab_region: 'Region Analysis',
    veg_tab_vision: 'Vision Analysis (Satellite/Drone)',
    veg_tab_map: 'Geographic Map',
    veg_input_placeholder: 'Enter Region Name...',
    veg_btn_analyze: 'Get Planting Plan',
    veg_upload_label: 'Upload Land Image or Map',
    veg_prompt_label: 'Your Question (Optional)',
    veg_prompt_placeholder: 'What trees are suitable for this slope?',
    veg_btn_vision: 'Analyze Image',
    veg_result_title: 'AI Recommendation',
    veg_region_empty: 'Enter a region name to get a planting plan.',
    veg_map_instr: 'Click on the map to get weather and groundwater forecasts.',
    veg_btn_map_analyze: 'Analyze Hydro-Climate',
    veg_btn_history: '5-Year Trend Analysis (NDVI)',
    veg_lat: 'Latitude',
    veg_lng: 'Longitude',

    // HydroMap Manager
    hydro_title: 'HydroMap AI',
    hydro_subtitle: 'Advanced Hydro-Climatic Analysis Platform',
    hydro_mode_point: 'Point Analysis',
    hydro_mode_basin: 'Basin Analysis',
    hydro_loading_analysis: 'Running Scientific Analysis...',
    hydro_chart_title: 'Historical Water Level Trend (NDWI Simulation)',
    hydro_basin_area: 'Basin Area',
    hydro_basin_perim: 'Basin Perimeter',
    hydro_tab_climate: 'Climate Forecast (Open-Meteo)',
    hydro_tab_hydro: 'Hydrology Status',
    hydro_tab_recs: 'AI Recommendations',

    dash_live: 'Live Aquifer Monitor',
    dash_static: 'Water Balance',
    dash_planning: 'Allocation Planning',
    dash_executive: 'Crisis Mgmt',
    chat_placeholder: 'Ask about plain status or water laws...',
    chat_send: 'Send',
    chat_clear: 'Clear',
    chat_processing: 'Hydro-Analysis...',
    chat_welcome: 'I am AbBaan. Which plain should I check?',
    chat_response: 'Expert Response',

    wp_dashboard: 'Violation Reports',
    wp_home: 'Protection Portal',
    wp_updates: 'Public Messages',
    wp_posts: 'Drought News',
    wp_media: 'Gallery',
    wp_pages: 'Water Cut Notices',
    wp_comments: 'Farmer Comments',
    wp_appearance: 'Theme',
    wp_plugins: 'Modules',
    wp_users: 'Users',
    wp_tools: 'Tools',
    wp_settings: 'Settings',
    wp_welcome_title: 'Water Whistleblowing System',
    wp_welcome_subtitle: 'Handling reports of illegal wells and excessive withdrawals.',
    wp_at_a_glance: 'Report Summary',
    wp_activity: 'Recent Violations',
    wp_quick_draft: 'Quick Minute',
    wp_news: 'Ministry News',
    wp_title_placeholder: 'Violation Subject',
    wp_content_placeholder: 'Description...',
    wp_save_draft: 'Save Draft',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fa');
  const [direction, setDirection] = useState<Direction>('rtl');

  useEffect(() => {
    const isRTL = language === 'fa';
    const dir = isRTL ? 'rtl' : 'ltr';
    setDirection(dir);
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
